name: Main GitHub Actions

on:
  push:    
    branches: 
      - 'master' 
  pull_request:
  workflow_dispatch:

jobs:

  test-job:    
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout        
        uses: actions/checkout@v4

      - name: Use Node 20        
        uses: actions/setup-node@v3
        with:          
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install
          
      - name: Compile TypeScript
        run: tsc
      
      - name: Run tests        
        run: jest